# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4b4c8f56bd4705e300bf06c501a62877c61e7342e26da2d49a03808531e72728ef8591b2b3a230b51a9a138ef38d3f80da4eec48a2f24a236342b00955bfc623

test:
  secret_key_base: f593559694fc3c228d78bc65775ee9b7312762551f26cdd0f00de247a140c06b1ac8f0aaecede77951be867c9e2904b57156fb982258e2ec9b3888834ea42356

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
